<Project>
  <PropertyGroup>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
    <FileVersion>1.0.0.0</FileVersion>
    <Version>1.0.0</Version>
    <ProductVersion>1.0.0</ProductVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Avalonia" />
		<PackageReference Include="CommunityToolkit.Mvvm" />
		<PackageReference Include="FluentValidation" />
		<PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
		<PackageReference Include="Newtonsoft.Json" />
		<PackageReference Include="System.ComponentModel.Composition" />
	</ItemGroup>
</Project>