<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
    <ApplicationIcon>proxy-checker.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <Content Include="proxy-checker.ico" />
  </ItemGroup>

  <ItemGroup>
		<PackageReference Include="Avalonia.Desktop" />
    <PackageReference Include="Avalonia.Themes.Fluent" />
    <PackageReference Include="Avalonia.Fonts.Inter" />
    <PackageReference Include="AvaloniaUI.DiagnosticsSupport">
      <IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
      <PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    <PackageReference Include="TextCopy" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ProxyChecker.Common\ProxyChecker.Common.csproj" />
    <ProjectReference Include="..\ProxyChecker.Interfaces\ProxyChecker.Interfaces.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="appsettings.local.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <Target Name="MakePluginsFolderAfterBuild" AfterTargets="Build">
	  <MakeDir Directories="$(TargetDir)Plugins" />
	  <MakeDir Directories="$(TargetDir)Plugins\Loaders" />
	  <MakeDir Directories="$(TargetDir)Plugins\Checkers" />
	  <MakeDir Directories="$(TargetDir)Plugins\Exporters" />
  </Target>
</Project>
